# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3"

services:
  bot:
    build: .
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true